[package]
name = "ray-tracing"
version = "0.0.1"
edition = "2021"
# build = "build.rs" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode_solvers = "0.3.7"
proj = {version="0.27.2", features=["pkg_config"]}
thiserror = "1.0.40"
