[package]
name = "ray-tracing"
version = "0.0.4"
edition = "2021"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.20.0"
libc = { version = "0.2", optional = true }
nalgebra = "0.32.3"
netcdf3 = "0.5.2"
netcdf = {version = "0.9.1", features = ["static"]}
ode_solvers = "0.4.0"
rayon = "1.8.1"
serde_json = "1.0.115"
serde = {version="1.0", features=["derive"]}
thiserror = "1.0.57"

[dev-dependencies]
lockfile = "0.4.0"
tempfile = "3.10.0"

[build-dependencies]
cbindgen = { version = "0.18.0", optional = true }

[features]
capi = ["libc"]
