[package]
name = "ray-tracing"
version = "0.0.4"
edition = "2021"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.20.0"
netcdf3 = "0.5.2"
ode_solvers = "0.4.0"
thiserror = "1.0.57"
nalgebra = "0.32.3"
rayon = "1.8.1"

[dev-dependencies]
lockfile = "0.4.0"
