[project]
name = "ray_tracing"
version = "0.1.0"
description = "Add a short description here"
authors = ["Gui Castelao <guilherme@castelao.net>"]
channels = ["conda-forge", "conda", "main"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
build = "cargo build"
develop = "maturin develop"
test = "cargo test"
fmt = "cargo fmt"
lint = { cmd = "cargo clippy", depends_on = ["fmt"], env = {} }
wheel = "maturin build"
pytest = { cmd = "pytest python/tests", depends_on = ["develop"], env = {} }

[dependencies]
maturin = ">=1.5.1,<1.6"
rust = ">=1.77.2,<1.78"
python = ">=3.10"
cffi = ">=1.16.0,<1.17"
pip = ">=24.0,<25"
xarray = ">=2023"
netcdf4 = ">=1.6.5,<1.7"
ruff = ">=0.4.9,<0.5"
matplotlib = ">=3.9.1,<3.10"
cmake = ">=3.30.5,<4"

[target.osx-arm64.build-dependencies]
m4 = ">=1.4.18,<1.5"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev", "test"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[feature.dev.dependencies]
ruff = ">=0.4"
ipython = ">=8.0"

[feature.test.dependencies]
pytest = ">=7.0"
netcdf4 = ">=1.5"
