name: Python checks

on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '4 5 * * 5'

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.7.3
          args: check
          src: "./python/mantaray"
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.7.3
          args: format --check
          src: "./python/mantaray"

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [beta, stable, windows, macos]
        include:
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: stable
            os: ubuntu-latest
            rust: stable
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          frozen: true
          cache: true

      - run: pixi run -e test pytest

  install:
    name: Test install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [beta, stable, windows, macos]
        include:
          - build: macos
            os: macos-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: stable
            os: ubuntu-latest
            rust: stable
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          frozen: true
          cache: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build wheel
        run: pixi run wheel --out dist --interpreter python3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest xarray netcdf4
          pip install dist/*

      - name: Run pytest
        continue-on-error: true
        run: pytest python/tests