name: Python documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.40.2
          cache: true
          frozen: true

      - name: Build HTML
        # Turn warning into errors
        run: SPHINXOPTS="-W --keep-going -n" pixi run -e docs python-docs
